<?php
/*
 You may not change or alter any portion of this comment or credits
 of supporting developers from this source code or any supporting source code
 which is considered copyrighted (c) material of the original comment or credit authors.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
 
defined("XOOPS_ROOT_PATH") or die("XOOPS root path not defined");

$modversion['name'] = _MI_xroster_NAME;
$modversion['version'] = 3.0;
$modversion['description'] = _MI_xroster_DESC;
$modversion['credits'] = 'SOE Gamers, redheadedrod';
$modversion['author'] = 'redheadedrod';
$modversion['help'] = '';
$modversion['license'] = 'GNU General Public License (GPL)';
$modversion['official'] = 0;
$modversion['image'] = 'images/xroster.png';
$modversion['dirname'] = basename(dirname(__FILE__));
$modversion['website'] = '';
$modversion['email'] = 'redheadedrod@hotmail.com';
// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';

// Menu
$modversion['hasMain'] = 1;
global $xoopsModule, $xoopsUser;
if ($xoopsModule && $xoopsModule->getVar('dirname') == $modversion['dirname']) {
  global $xoopsModuleConfig;
  if($xoopsModuleConfig['xrosterapplication'] == 1) {
    $modversion['sub'][1]['name'] = 'Application';
    $modversion['sub'][1]['url'] = 'index.php?op=Apply';
  }
}

  $xrostergroups = array();
  $member_handler =& xoops_gethandler('member');
  $getgroups =& $member_handler->getGroups();
  $count = count($getgroups);
  for ($i = 0; $i < $count; $i++) {
    $id = $getgroups[$i]->getVar('groupid');
	if ($id != 3) $xrostergroups[$getgroups[$i]->getVar('name')] = $id;
  }	


// Templates
$i = 0;

$i++;
$modversion['templates'][$i]['file'] = 'xroster_index_template.html'; // main index
$modversion['templates'][$i]['description'] = 'xroster';

// Blocks
$i = 0;

$i++;
$modversion['blocks'][$i]['file'] = 'xroster_blocks.php';
$modversion['blocks'][$i]['name'] = _MD_xroster_BLOCK1_NAME;
$modversion['blocks'][$i]['description']	= _MD_xroster_BLOCK1_DESC;
$modversion['blocks'][$i]['show_func'] = 'b_xroster_newestmember_show';
$modversion['blocks'][$i]['template'] = 'xroster_block_newestmember.html';
$modversion['blocks'][$i]['file'] = 'xroster_blocks.php';
$modversion['blocks'][$i]['name'] = _MD_xroster_BLOCK2_NAME;
$modversion['blocks'][$i]['description']	= _MD_xroster_BLOCK2_DESC;
$modversion['blocks'][$i]['show_func'] = 'b_xroster_randommember_show';
$modversion['blocks'][$i]['template'] = 'xroster_block_randommember.html';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/data.sql';

// Tables created by sql file (without prefix!)
$modversion['tables'] = array('xroster', 'xroster_titles', 'xroster_groups', 'xroster_categories', 'xroster_lang', 'xroster_userinfo');

// Comments
$modversion['hasComments'] = 0;
$modversion['comments']['itemName'] = 'cid';
$modversion['comments']['pageName'] = 'comments.php';

// Search
$modversion['hasSearch'] = 0;
$modversion['search']['file'] = 'include/search.inc.php';
$modversion['search']['func'] = 'module_search';

// Config categories

$modversion['configcat']['opts']['name'] = _MI_xroster_CONFCAT_OPTS;
$modversion['configcat']['opts']['description'] = _MI_xroster_CONFCAT_OPTS_DESC;

$modversion['configcat']['visable']['name'] = _MI_xroster_CONFCAT_BASE;
$modversion['configcat']['visable']['description'] = _MI_xroster_CONFCAT_BASE_DESC;

//Config
$i = 0;

// Module options

$i++;
$modversion['config'][$i]['name'] = 'xrosterapplication';
$modversion['config'][$i]['title'] ='_MD_xroster_APPLICATION';
$modversion['config'][$i]['description'] ='_MD_xroster_APPLICATION_DESC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = '1';
$modversion['config'][$i]['category'] = 'opts';
/*
$i++;
$modversion['config'][$i]['name'] = 'usetitle';
$modversion['config'][$i]['title'] = '_MD_xroster_UTITLE';
$modversion['config'][$i]['description'] = '_MD_xroster_UTITLE_DESC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = '1';
$modversion['config'][$i]['category'] = 'opts';

$i++;
$modversion['config'][$i]['name'] = 'usegroup';
$modversion['config'][$i]['title'] = '_MD_xroster_UGROUP';
$modversion['config'][$i]['description'] = '_MD_xroster_UGROUP_DESC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = '1';
$modversion['config'][$i]['category'] = 'opts';  */

$i++;
$modversion['config'][$i]['name'] = 'heading';
$modversion['config'][$i]['title'] = '_MI_xroster_HEADING';
$modversion['config'][$i]['description'] = '_MI_xroster_HEADING_DESC';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'If you feel you have what it takes... <br>The commitment and the dedication...  <br>Please provide the following contact information<br>Fields marked with an asterix (*) are mandatory,<br>forms without these fields filled out properly won\'t be processed.';
$modversion['config'][$i]['category'] = 'opts';

$i++;
$modversion['config'][$i]['name'] = 'agreement';
$modversion['config'][$i]['title'] = '_MD_xroster_AGREEMENT';
$modversion['config'][$i]['description'] = '_MD_xroster_AGREEMENT_DESC';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'Please note that by applying does not mean you\'re automatically a player. You must come to practices and the coaches will decide if you are a player or not.';
$modversion['config'][$i]['category'] = 'opts';

$i++;
$modversion['config'][$i]['name'] = 'agreement2';
$modversion['config'][$i]['title'] = '_MD_xroster_AGREEMENT2';
$modversion['config'][$i]['description'] = '_MD_xroster_AGREEMENT2_DESC';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'By filling out this form you agree that you have read, and are aware of, the code of conduct as stated here.';
$modversion['config'][$i]['category'] = 'opts';

$i++;
$modversion['config'][$i]['name'] = 'mail2admin';
$modversion['config'][$i]['title'] = '_MD_xroster_MAIL2ADMIN';
$modversion['config'][$i]['description'] = '_MD_xroster_MAIL2ADMIN_DESC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = '0';

$i++;
$modversion['config'][$i]['name'] = 'mailonedit';
$modversion['config'][$i]['title'] = '_MD_xroster_MAILONEDIT';
$modversion['config'][$i]['description'] = '_MD_xroster_MAILONEDIT_DESC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = '0'; 

$i++;
$modversion['config'][$i]['name'] = 'adminmail';
$modversion['config'][$i]['title'] = '_MD_xroster_ADMINMAIL';
$modversion['config'][$i]['description'] = '_MD_xroster_ADMINMAIL_DESC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = $xoopsConfig['adminmail'];
$modversion['config'][$i]['category'] = 'opts';

$i++;
$modversion['config'][$i]['name'] = 'ppicpath';
$modversion['config'][$i]['title'] = '_MD_xroster_PPICPATH';
$modversion['config'][$i]['description'] = '_MD_xroster_PPICPATH_DESC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = XOOPS_ROOT_PATH . "/modules/" . $modversion['dirname'] . "/images/";
$modversion['config'][$i]['category'] = 'opts';

$i++;
$modversion['config'][$i]['name'] = 'groupadd';
$modversion['config'][$i]['title'] = '_MD_xroster_GROUPADD';
$modversion['config'][$i]['description'] = '_MD_xroster_GROUPADD_DESC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = '0';

$i++;
$modversion['config'][$i]['name'] = 'ugroup';
$modversion['config'][$i]['title'] = '_MD_xroster_UGROUPS';
$modversion['config'][$i]['description'] = '_MD_xroster_UGROUPS_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '2';
$modversion['config'][$i]['options'] = $xrostergroups;

$i++;
$modversion['config'][$i]['name'] = 'editdirty';
$modversion['config'][$i]['title'] = '_MD_xroster_EDITDIRTY';
$modversion['config'][$i]['description'] = '_MD_xroster_EDITDIRTY_DESC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = '0'; 

//visability settings

$i++;
$modversion['config'][$i]['name'] = 'vemail';
$modversion['config'][$i]['title'] = '_MD_xroster_VEMAIL';
$modversion['config'][$i]['description'] = '_MD_xroster_VEMAIL_DESC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = '0';
$modversion['config'][$i]['category'] = 'visable';

$i++;
$modversion['config'][$i]['name'] = 'vname';
$modversion['config'][$i]['title'] = '_MD_xroster_VNAME';
$modversion['config'][$i]['description'] = '_MD_xroster_VNAME_DESC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = '0';
$modversion['config'][$i]['category'] = 'visable';

?>