<?php

$modversion['name'] = 'xRoster';
$modversion['version'] = '2.2.3';
$modversion['description'] = _MD_XROSTER_MODDESC;
$modversion['credits'] = 'SOE Gamers';
$modversion['author'] = 'SOE Gamers';
$modversion['help'] = 'xRoster_help.html';
$modversion['license'] = 'GPL';
$modversion['official'] = 0;
$modversion['image'] = 'xroster.png';
$modversion['dirname'] = 'xroster';
$modversion['website'] = 'www.soegamers.com';
$modversion['email'] = 'churchill@soegamers.com';
// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';

// Menu
$modversion['hasMain'] = 1;
global $xoopsModule;
if ($xoopsModule && $xoopsModule->getVar('dirname') == $modversion['dirname']) {
  global $xoopsModuleConfig;
  if($xoopsModuleConfig['xrosterapplication'] == 1) {
    $modversion['sub'][1]['name'] = 'Application';
    $modversion['sub'][1]['url'] = 'index.php?op=Apply';
  }
}

// Templates
$modversion['templates'][1]['file'] = 'index_template.html'; // main index
$modversion['templates'][1]['description'] = 'xRoster';

// Blocks
$modversion['blocks'][1]['file'] = 'xroster_blocks.php';
$modversion['blocks'][1]['name'] = _MD_XROSTER_BLOCK1_NAME;
$modversion['blocks'][1]['description']	= _MD_XROSTER_BLOCK1_DESC;
$modversion['blocks'][1]['show_func'] = 'b_xroster_newestmember_show';
$modversion['blocks'][1]['template'] = 'xroster_block_newestmember.html';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/data.sql';

// Tables created by sql file (without prefix!)
$modversion['tables'] = array('xRoster', 'xRoster_titles', 'xRoster_groups', 'xRoster_categories');

// Comments
$modversion['hasComments'] = 0;
$modversion['comments']['itemName'] = 'cid';
$modversion['comments']['pageName'] = 'comments.php';

// Search
$modversion['hasSearch'] = 0;
$modversion['search']['file'] = 'include/search.inc.php';
$modversion['search']['func'] = 'module_search';

//Config
$modversion['config'] = array(
  array(
    'name'=>'xrosterapplication',
    'title'=>'_MD_XROSTER_APPLICATION',
    'description'=>'_MD_XROSTER_APPLICATION_DESC',
    'formtype'=>'select',
    'valuetype'=>'int',
    'default'=>'1',
    'options'=>array('Off'=>0, 'On'=>1)),
  array(
    'name'=>'hidemail',
    'title'=>'_MD_XROSTER_HIDEMAIL',
    'description'=>'_MD_XROSTER_HIDEMAIL_DESC',
    'formtype'=>'select',
    'valuetype'=>'int',
    'default'=>'0',
    'options'=>array('Off'=>0, 'On'=>1)),
  array(
    'name'=>'adminmail',
    'title'=>'_MD_XROSTER_ADMINMAIL',
    'description'=>'_MD_XROSTER_ADMINMAIL_DESC',
    'formtype'=>'text',
    'valuetype'=>'string',
    'default'=>$xoopsConfig['adminmail']));
?>